# Docker
jobs:
- job: 
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: 'aks-deploy-from-acr.yaml'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd32bbfbe-34c8-4a03-bf6b-f64e6c650840'
  imageRepository: 'harshadarshdepartmentfinal'
  containerRegistry: 'harshacrrepo4321.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
