#Docker-compose.yml
version: '3.9'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Iamthebest*2001
      MYSQL_DATABASE: usersdb
    ports:
      - "3307:3306"
  #app:
    #image: my-spring-boot-app
    #ports:
     # - "9090:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
      
      
  app:
    image: my-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - database
      - rabbitmq
      - redis
      - fakesmtp
    ports:
      - "9090:8080"
    links:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/usersdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Iamthebest*2001
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE_NAME: department-queue
      RABBITMQ_QUEUE_DURABLE: true
      RABBITMQ_EXCHANGE_NAME: department-exchange
      RABBITMQ_BINDING_ROUTING_KEY: myRoutingKey

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

    
  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - "25:25"
    environment:
      - EMAIL_STORAGE=/var/mail
