replicaCount: 1
 
image:
  repository: harshadarsh2001/my-spring-boot2
  pullPolicy: IfNotPresent
  tag: latest
 
 
service:
  type: ClusterIP
 
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/usersdb
    username: root
    password: Iamthebest*2001
 
rabbitmq:
  host: rabbitmq
  port: 5672
  queue:
    name: department-queue
    durable: true
  exchange:
    name: department-exchange
  binding:
    routingKey: myRoutingKey
 
mysql:
  rootPassword: "Iamthebest*2001"
  database: "usersdb"
 
ingress:
  enabled: true
  annotations:
  # Add your desired annotations here
  hosts:
    - host: myapp.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
serviceAccount:
  create: true
 
autoscaling:
  enabled: false