replicaCount: 1

image:
  repository: my-spring-boot-app
  tag: latest

service:
  type: ClusterIP
  
spring:
  datasource:
    url: jdbc:mysql://database:3306/usersdb?useSSL=true&requireSSL=true
    username: root
    password: Iamthebest*2001

rabbitmq:
  host: rabbitmq
  port: 5672
  queue:
    name: department-queue
    durable: true
  exchange:
    name: department-exchange
  binding:
    routingKey: myRoutingKey
mysql:
  rootPassword: Iamthebest*2001
  database: usersdb
