replicaCount: 1

image:
  repository: harshadarsh2001/my-spring-boot-app
  pullPolicy: IfNotPresent
  tag: latest

mySpringBootApplication:
  image:
    repository: harshadarsh2001/my-spring-boot-app
    tag: latest

service:
  type: ClusterIP
  
spring:
  datasource:
    url: jdbc:mysql://database:3306/usersdb?useSSL=true&requireSSL=true
    username: root
    password: Iamthebest*2001

rabbitmq:
  host: rabbitmq
  port: 5672
  queue:
    name: department-queue
    durable: true
  exchange:
    name: department-exchange
  binding:
    routingKey: myRoutingKey

mysql:
  rootPassword: Iamthebest*2001
  database: usersdb

ingress:
  enabled: false
  annotations: 
    # Add your desired annotations here
  hosts:
    - host: my-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
